# Site settings
title: Jack A. Pickus
email: jackpickus@outlook.com
description: A portfolio website about Jack Pickus
baseurl: ""
url: "http://yourdomain.com"
picture: /assets/images/image.jpg
og_picture: /assets/images/og.png
github_username:  jackpickus
linkedin_username: jackpickus
twitter_username: jackpickus

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

port: 8000
