# Site settings
title: Jack A. Pickus
email: pickus@cs.wisc.edu
description: A portfolio website about Jack Pickus
baseurl: ""
url: "http://yourdomain.com"
picture: /assets/images/image.jpg
github_username:  jackpickus
linkedin_username: jackpickus
twitter_username: jackpickus

# Build settings
markdown: kramdown
permalink: pretty

port: 8000
